
_screen_lib8_final_stage_complete:
		.WORD _scr8_0
		.WORD _scr8_1
		.WORD _scr8_2
		.WORD _scr8_3
_scr8_0:
		.BYTE $34,$D8,$27,$37,$27,$2B,$2B,$2C,$27,$37,$27,$27,$27,$29,$27,$27
		.BYTE $27,$2B,$2C,$27,$29,$2B,$2B,$2C,$2B,$2E,$2C,$2E,$2C,$38,$2C,$2A
		.BYTE $2D,$2C,$34,$04,$27,$36,$27,$2B,$2C,$27,$39
_scr8_1:
		.BYTE $27,$27,$2A,$2D,$2E,$2E,$2C,$28,$2E,$2C,$2E,$2C,$2F,$28,$28,$4F
		.BYTE $00,$00,$46,$3F,$2E,$2C,$3D,$2E,$2E,$2C,$38,$3F,$2E,$36,$27,$27
		.BYTE $27,$27,$27,$2B,$2F,$3F,$34,$04,$28,$3D,$3C,$3D,$28,$5E,$5F,$8B
		.BYTE $8B,$56,$28,$28,$3D,$2F,$2F,$36,$2F,$34,$04,$28,$2E,$2C,$27,$29
		.BYTE $27,$27,$3E,$2F,$3D,$2F,$3F,$3C,$2F,$28,$28,$28,$6E,$6F,$99,$9A
		.BYTE $9B,$34,$06,$28,$2F,$3D,$3D,$2F,$2F,$36,$36,$27,$27,$27,$2A,$2F
		.BYTE $34,$09,$28,$7E,$7F,$8A,$8A,$AB,$34,$04,$28,$2F,$2F,$34,$04,$28
		.BYTE $3F,$35,$3B,$34,$04,$27,$3E,$3B,$3E,$3A,$3E,$3B,$3A,$3E,$48,$49
		.BYTE $4A,$4B,$00,$8B,$00,$BC,$3B,$27,$3E,$35,$3B,$36,$3A,$43,$37,$27
		.BYTE $27,$27,$34,$06,$27,$30,$31,$32,$34,$04,$27,$59,$5A,$5B,$00,$8A
		.BYTE $8A,$BB,$2B,$2B,$2C,$34,$09,$27,$34,$06,$27,$40,$41,$42,$27,$88
		.BYTE $67,$68,$69,$E2,$6B,$AA,$8B,$AA,$BA,$27,$3A,$34,$0A,$27,$34,$06
		.BYTE $27,$50,$27,$27,$27,$8B,$8A,$78,$79,$7A,$6B,$00,$8A,$8A,$B9,$87
		.BYTE $88,$87,$67,$34,$08,$27,$39
_scr8_2:
		.BYTE $60,$61,$34,$04,$27,$76,$27,$88,$69,$8A,$8B,$8C,$79,$00,$00,$8A
		.BYTE $00,$00,$00,$79,$A9,$79,$8A,$27,$27,$67,$A8,$A8,$27,$27,$27,$70
		.BYTE $71,$72,$73,$74,$75,$76,$77,$98,$79,$00,$8A,$34,$0C,$00,$A9,$A9
		.BYTE $00,$B8,$B8,$77,$74,$75,$80,$81,$82,$83,$84,$85,$95,$95,$86,$94
		.BYTE $86,$86,$00,$95,$86,$00,$00,$00,$95,$94,$95,$95,$00,$00,$95,$95
		.BYTE $86,$86,$86,$94,$84,$85,$90,$91,$92,$93,$94,$94,$95,$94,$95,$94
		.BYTE $27,$94,$27,$94,$95,$94,$95,$94,$94,$95,$94,$94,$95,$94,$94,$27
		.BYTE $94,$95,$95,$A4,$B6,$A4,$A0,$A1,$A2,$34,$05,$27,$A4,$A5,$A6,$A5
		.BYTE $B6,$A5,$B6,$A4,$A6,$27,$27,$A7,$A7,$A5,$A6,$B5,$B6,$A5,$B6,$A5
		.BYTE $B5,$A5,$27,$27,$B0,$B1,$B2,$B3,$A4,$A4,$A5,$A4,$A6,$A4,$A6,$A4
		.BYTE $27,$A4,$A7,$A6,$A5,$A6,$B5,$27,$27,$27,$A4,$B6,$B5,$27,$27,$A4
		.BYTE $B5,$A4,$B5,$A4,$27,$A4,$A5,$A6,$B3,$34,$05,$27,$A4,$B5,$A6,$A4
		.BYTE $A7,$A5,$27,$27,$27,$A4,$A5,$A4,$B5,$27,$27,$27,$A4,$A5,$27,$27
		.BYTE $27,$B3,$27,$27,$B4,$27,$A4,$A7,$A5,$A6,$34,$15,$27,$B3,$27,$B4
		.BYTE $39
_scr8_3:
		.BYTE $27,$B3,$34,$1D,$27,$B3,$27,$27,$27,$B7,$27,$B4,$27,$27,$B4,$27
		.BYTE $27,$B3,$34,$0B,$27,$B4,$34,$06,$27,$B7,$27,$B4,$27,$27,$27,$B3
		.BYTE $34,$0E,$27,$B4,$34,$08,$27,$B3,$27,$27,$27,$27,$27,$B3,$34,$05
		.BYTE $27,$B3,$34,$05,$27,$B4,$34,$05,$27,$B3,$34,$04,$27,$B3,$34,$05
		.BYTE $27,$B4,$34,$04,$00,$34,$04,$C0,$34,$1C,$00,$34,$04,$C0,$34,$18
		.BYTE $00,$34,$34,$23,$C0,$34,$20,$00,$34,$08,$50,$34,$10,$55,$00,$05
		.BYTE $00,$0F,$0C,$03,$03,$0F,$39
_spr73:
		.BYTE $01
		.WORD $1000
		.BYTE $00,$03,$00,$04
_spr74:
		.BYTE $02
		.WORD $1008
		.BYTE $00,$05,$00,$00
		.BYTE $00,$07,$00,$08
_spr75:
		.BYTE $02
		.WORD $1008
		.BYTE $00,$09,$00,$00
		.BYTE $00,$0B,$00,$08
_spr76:
		.BYTE $02
		.WORD $1008
		.BYTE $00,$0D,$00,$00
		.BYTE $00,$0F,$00,$08
_spr77:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$11,$00,$00
		.BYTE $10,$13,$00,$00
		.BYTE $00,$15,$00,$08
		.BYTE $10,$17,$00,$08
_spr78:
		.BYTE $05
		.WORD $0008
		.BYTE $00,$19,$00,$00
		.BYTE $10,$1B,$00,$00
		.BYTE $00,$1D,$00,$08
		.BYTE $10,$1F,$00,$08
		.BYTE $00,$21,$00,$10
_spr79:
		.BYTE $05
		.WORD $0008
		.BYTE $00,$23,$00,$F8
		.BYTE $00,$25,$00,$00
		.BYTE $10,$27,$00,$00
		.BYTE $00,$29,$00,$08
		.BYTE $10,$2B,$00,$08
_spr7A:
		.BYTE $08
		.WORD $FB08
		.BYTE $00,$2D,$00,$F8
		.BYTE $F0,$2F,$00,$00
		.BYTE $00,$31,$00,$00
		.BYTE $10,$33,$00,$00
		.BYTE $F0,$35,$00,$08
		.BYTE $00,$37,$00,$08
		.BYTE $10,$39,$00,$08
		.BYTE $00,$3B,$00,$10
_spr7B:
		.BYTE $07
		.WORD $0008
		.BYTE $F8,$3D,$00,$F0
		.BYTE $F0,$3F,$00,$F8
		.BYTE $00,$41,$00,$F8
		.BYTE $F0,$43,$00,$00
		.BYTE $00,$45,$00,$00
		.BYTE $10,$47,$00,$00
		.BYTE $F0,$49,$00,$08
_spr80:
		.BYTE $02
		.WORD $0008
		.BYTE $00,$4D,$00,$00
		.BYTE $00,$4F,$00,$08
_spr81:
		.BYTE $08
		.WORD $F808
		.BYTE $00,$51,$00,$F8
		.BYTE $10,$59,$00,$F8
		.BYTE $00,$53,$00,$00
		.BYTE $10,$5B,$00,$00
		.BYTE $00,$55,$00,$08
		.BYTE $10,$5D,$00,$08
		.BYTE $00,$57,$00,$10
		.BYTE $10,$5F,$00,$10
_spr82:
		.BYTE $12
		.WORD $F008
		.BYTE $00,$61,$00,$F0
		.BYTE $10,$6D,$00,$F0
		.BYTE $20,$79,$00,$F0
		.BYTE $00,$63,$00,$F8
		.BYTE $10,$6F,$00,$F8
		.BYTE $20,$7B,$00,$F8
		.BYTE $00,$65,$00,$00
		.BYTE $10,$71,$00,$00
		.BYTE $20,$7D,$00,$00
		.BYTE $00,$67,$00,$08
		.BYTE $10,$73,$00,$08
		.BYTE $20,$7F,$00,$08
		.BYTE $00,$69,$00,$10
		.BYTE $10,$75,$00,$10
		.BYTE $20,$81,$00,$10
		.BYTE $00,$6B,$00,$18
		.BYTE $10,$77,$00,$18
		.BYTE $20,$83,$00,$18
_spr83:
		.BYTE $12
		.WORD $F008
		.BYTE $00,$85,$00,$F0
		.BYTE $10,$91,$00,$F0
		.BYTE $20,$9D,$00,$F0
		.BYTE $00,$87,$00,$F8
		.BYTE $10,$93,$00,$F8
		.BYTE $20,$9F,$00,$F8
		.BYTE $00,$89,$00,$00
		.BYTE $10,$95,$00,$00
		.BYTE $20,$A1,$00,$00
		.BYTE $00,$8B,$00,$08
		.BYTE $10,$97,$00,$08
		.BYTE $20,$A3,$00,$08
		.BYTE $00,$8D,$00,$10
		.BYTE $10,$99,$00,$10
		.BYTE $20,$A5,$00,$10
		.BYTE $00,$8F,$00,$18
		.BYTE $10,$9B,$00,$18
		.BYTE $20,$A7,$00,$18
_spr84:
		.BYTE $1D
		.WORD $E008
		.BYTE $00,$A9,$00,$E8
		.BYTE $10,$B7,$00,$E8
		.BYTE $30,$D3,$00,$E8
		.BYTE $00,$AB,$00,$F0
		.BYTE $10,$B9,$00,$F0
		.BYTE $20,$C7,$00,$F0
		.BYTE $30,$D5,$00,$F0
		.BYTE $00,$AD,$00,$F8
		.BYTE $10,$BB,$00,$F8
		.BYTE $20,$C9,$00,$F8
		.BYTE $30,$D7,$00,$F8
		.BYTE $00,$AF,$00,$00
		.BYTE $10,$BD,$00,$00
		.BYTE $20,$CB,$00,$00
		.BYTE $30,$D9,$00,$00
		.BYTE $00,$B1,$00,$08
		.BYTE $10,$BF,$00,$08
		.BYTE $20,$CD,$00,$08
		.BYTE $30,$DB,$00,$08
		.BYTE $00,$B3,$00,$10
		.BYTE $10,$C1,$00,$10
		.BYTE $20,$CF,$00,$10
		.BYTE $30,$DD,$00,$10
		.BYTE $00,$B5,$00,$18
		.BYTE $10,$C3,$00,$18
		.BYTE $20,$D1,$00,$18
		.BYTE $30,$DF,$00,$18
		.BYTE $10,$C5,$00,$20
		.BYTE $30,$E1,$00,$20
_spr85:
		.BYTE $1A
		.WORD $E008
		.BYTE $30,$C8,$00,$E8
		.BYTE $00,$E3,$00,$F0
		.BYTE $10,$EF,$00,$F0
		.BYTE $20,$FD,$00,$F0
		.BYTE $30,$D0,$00,$F0
		.BYTE $00,$E5,$00,$F8
		.BYTE $10,$F1,$00,$F8
		.BYTE $20,$FF,$00,$F8
		.BYTE $30,$D2,$00,$F8
		.BYTE $00,$E7,$00,$00
		.BYTE $10,$F3,$00,$00
		.BYTE $20,$DC,$00,$00
		.BYTE $30,$D4,$00,$00
		.BYTE $00,$E9,$00,$08
		.BYTE $10,$F5,$00,$08
		.BYTE $20,$C2,$00,$08
		.BYTE $30,$D6,$00,$08
		.BYTE $00,$EB,$00,$10
		.BYTE $10,$F7,$00,$10
		.BYTE $20,$C4,$00,$10
		.BYTE $30,$D8,$00,$10
		.BYTE $10,$F9,$00,$18
		.BYTE $20,$C6,$00,$18
		.BYTE $30,$E0,$00,$18
		.BYTE $10,$FB,$00,$20
		.BYTE $30,$E2,$00,$20
_spr86:
		.BYTE $13
		.WORD $F008
		.BYTE $20,$FA,$00,$E8
		.BYTE $00,$E4,$00,$F0
		.BYTE $10,$F0,$00,$F0
		.BYTE $20,$FC,$00,$F0
		.BYTE $00,$E6,$00,$F8
		.BYTE $10,$F2,$00,$F8
		.BYTE $20,$CA,$00,$F8
		.BYTE $00,$E8,$00,$00
		.BYTE $10,$C2,$00,$00
		.BYTE $20,$CC,$00,$00
		.BYTE $00,$EA,$00,$08
		.BYTE $10,$F4,$00,$08
		.BYTE $20,$DA,$00,$08
		.BYTE $00,$EC,$00,$10
		.BYTE $10,$F6,$00,$10
		.BYTE $20,$CE,$00,$10
		.BYTE $00,$EE,$00,$18
		.BYTE $10,$F8,$00,$18
		.BYTE $20,$DE,$00,$18
_spr8A:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$1B,$00,$00
		.BYTE $10,$1D,$00,$00
		.BYTE $00,$1F,$00,$08
		.BYTE $10,$21,$00,$08
_spr8B:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$23,$00,$00
		.BYTE $10,$25,$00,$00
		.BYTE $00,$27,$00,$08
		.BYTE $10,$29,$00,$08
_spr8C:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$2B,$00,$00
		.BYTE $10,$2D,$00,$00
		.BYTE $00,$2F,$00,$08
		.BYTE $10,$31,$00,$08
_spr8E:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$33,$00,$00
		.BYTE $10,$35,$00,$00
		.BYTE $00,$37,$00,$08
		.BYTE $10,$21,$00,$08
_spr8F:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$39,$00,$00
		.BYTE $10,$3B,$00,$00
		.BYTE $00,$3D,$00,$08
		.BYTE $10,$3F,$00,$08
_spr90:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$41,$00,$00
		.BYTE $10,$43,$00,$00
		.BYTE $00,$45,$00,$08
		.BYTE $10,$47,$00,$08
_spr92:
		.BYTE $07
		.WORD $0008
		.BYTE $00,$49,$00,$F8
		.BYTE $10,$51,$00,$F8
		.BYTE $00,$4B,$00,$00
		.BYTE $10,$53,$00,$00
		.BYTE $00,$4D,$00,$08
		.BYTE $10,$55,$00,$08
		.BYTE $00,$4F,$00,$10
_spr93:
		.BYTE $04
		.WORD $0008
		.BYTE $10,$57,$00,$F8
		.BYTE $10,$59,$00,$00
		.BYTE $10,$5B,$00,$08
		.BYTE $10,$5D,$00,$10
_spr94:
		.BYTE $07
		.WORD $0008
		.BYTE $00,$73,$00,$F8
		.BYTE $10,$7B,$00,$F8
		.BYTE $00,$75,$00,$00
		.BYTE $10,$7D,$00,$00
		.BYTE $00,$77,$00,$08
		.BYTE $10,$7F,$00,$08
		.BYTE $00,$79,$00,$10
_spr95:
		.BYTE $06
		.WORD $0008
		.BYTE $10,$87,$00,$F8
		.BYTE $00,$81,$00,$00
		.BYTE $10,$89,$00,$00
		.BYTE $00,$83,$00,$08
		.BYTE $10,$8B,$00,$08
		.BYTE $00,$85,$00,$10
_spr96:
		.BYTE $08
		.WORD $0008
		.BYTE $00,$5F,$00,$F8
		.BYTE $10,$67,$00,$F8
		.BYTE $00,$61,$00,$00
byte_53DD1:
		.BYTE $10,$69,$00,$00
		.BYTE $00,$63,$00,$08
		.BYTE $10,$6B,$00,$08
		.BYTE $00,$65,$00,$10
		.BYTE $10,$6D,$00,$10
_spr97:
		.BYTE $08
		.WORD $0008
		.BYTE $00,$6F,$00,$F8
		.BYTE $10,$67,$00,$F8
		.BYTE $00,$71,$00,$00
		.BYTE $10,$69,$00,$00
		.BYTE $00,$63,$00,$08
		.BYTE $10,$6B,$00,$08
		.BYTE $00,$65,$00,$10
		.BYTE $10,$6D,$00,$10
_spr98:
		.BYTE $06
		.WORD $0008
		.BYTE $10,$91,$00,$F8
		.BYTE $00,$8D,$00,$00
		.BYTE $10,$93,$00,$00
		.BYTE $00,$8F,$00,$08
		.BYTE $10,$95,$00,$08
		.BYTE $10,$97,$00,$10
_spr99:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$A7,$00,$00
		.BYTE $10,$99,$00,$00
		.BYTE $00,$A9,$00,$08
		.BYTE $10,$9B,$00,$08
_spr9A:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$AB,$00,$00
		.BYTE $10,$99,$00,$00
		.BYTE $00,$AD,$00,$08
		.BYTE $10,$9D,$00,$08
_spr9B:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$AF,$00,$00
		.BYTE $10,$99,$00,$00
		.BYTE $00,$B1,$00,$08
		.BYTE $10,$B7,$00,$08
_spr9C:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$B3,$00,$00
		.BYTE $10,$99,$00,$00
		.BYTE $00,$B5,$00,$08
		.BYTE $10,$B7,$00,$08
_spr9D:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$A7,$00,$00
		.BYTE $10,$99,$00,$00
		.BYTE $00,$A9,$00,$08
		.BYTE $10,$9B,$00,$08
_spr9E:
		.BYTE $04
		.WORD $0008
		.BYTE $00,$AB,$00,$00
		.BYTE $10,$99,$00,$00
		.BYTE $00,$AD,$00,$08
		.BYTE $10,$9D,$00,$08

; =============== S U B	R O U T	I N E =======================================
_ending00:
		JSR		_fds_load_bufs_clear
		LDA		#$00
		STA		byte_540
		INC		_sub_sub_idx
		LDA		#$B0
		STA		byte_6C4
		JSR		_type_msg_ending_fetch
		RTS

; =============== S U B	R O U T	I N E =======================================
_ending01:
		JSR		_type_msg_handler
		LDA		_frames_counter
		AND		#$03
		BNE		locret_53EC1
		DEC		byte_6C4
		BNE		locret_53EC1
		LDA		_2p_stage
		CMP		#$08
		BCC		loc_53EBF
		JMP		sub_8A5D
; ---------------------------------------------------------------------------
loc_53EBF:
		INC		_sub_sub_idx
locret_53EC1:
		RTS

; =============== S U B	R O U T	I N E =======================================
_ending04:
		LDX		#$00

; =============== S U B	R O U T	I N E =======================================
sub_53EC4:
		LDA		byte_55F,X
		JSR		_switch
; ---------------------------------------------------------------------------
		.WORD sub_53ED8
		.WORD sub_53FCE
		.WORD sub_53FF2
		.WORD sub_5402E
		.WORD sub_54049
		.WORD sub_54074
		.WORD sub_54078

; =============== S U B	R O U T	I N E =======================================
sub_53ED8:
		CPX		#$60
		BCC		loc_53EDF
		JMP		loc_53FB9
; ---------------------------------------------------------------------------
loc_53EDF:
		LDA		_frames_counter
		AND		#$3F
		BNE		loc_53F24
		DEC		byte_55D,X
		BNE		loc_53F24
		LDA		#$06
		STA		byte_5A0+$1F
		STA		byte_5C0+$1F
		LDA		_1p_lives
		BEQ		loc_53F03
		LDA		#$01
		STA		byte_5A0
		LDA		_players_num
		BEQ		loc_53F0B
		LDA		_2p_lives
		BEQ		loc_53F0B
loc_53F03:
		LDA		#$01
		STA		byte_5C0
		STA		byte_5C0+$B
loc_53F0B:
		LDA		#$04
		STA		byte_55F,X
		LDA		#$99
		CPX		#$00
		BEQ		loc_53F18
		LDA		#$9B
loc_53F18:
		STA		byte_54F,X
		LDA		#$FF
loc_53F1D:
		STA		byte_55E,X
		TXA
		JMP		loc_53FC0
; ---------------------------------------------------------------------------
loc_53F24:
		LDA		_frames_counter
		AND		#$0F
		BNE		loc_53F8E
		CPX		#$40
		BNE		loc_53F8E
		DEC		byte_55E,X
		LDA		byte_55E,X
		CMP		#$65
		BEQ		loc_53F72
		CMP		#$00
		BNE		loc_53F8E
		LDA		#$1E
		STA		byte_541,X
		JSR		sub_89FB
		LDA		#$00
		STA		byte_553,X
		INC		byte_55F,X
		LDA		#$50
		STA		byte_55E,X
		LDY		#$A0
loc_53F53:
		LDA		#$01
		STA		byte_540,Y
		LDA		byte_543,X
		SEC
		SBC		#$10
		STA		byte_543,Y
		LDA		byte_545,X
		SEC
		SBC		#$20
		STA		byte_545,Y
		LDA		#$24
		STA		byte_55E,Y
		JMP		loc_53FB9
; ---------------------------------------------------------------------------
loc_53F72:
		LDA		#$1F
		STA		byte_541,X
		JSR		sub_89FB
		LDA		#$00
		STA		byte_553,X
		INC		byte_55F,X
		INC		byte_55F,X
		LDA		#$D8
		STA		byte_55E,X
		LDY		#$C0
		BNE		loc_53F53
loc_53F8E:
		TXA
		BEQ		loc_53FA6
		LDA		byte_543
		SEC
		SBC		byte_543,X
		CPX		#$20
		BEQ		loc_53FA2
		CMP		#$80
		BCS		loc_53FAC
		BCC		loc_53FA6
loc_53FA2:
		CMP		#$40
		BCS		loc_53FAC
loc_53FA6:
		LDA		_frames_counter
		AND		#$01
		BNE		loc_53FB9
loc_53FAC:
		INC		byte_543,X
		LDA		byte_543,X
		BNE		loc_53FB9
		LDA		#$01
		STA		byte_540,X
loc_53FB9:
		TXA
		TAY
		JSR		sub_C324
		TYA
		TAX
loc_53FC0:
		CLC
		ADC		#$20
		TAX
		CPX		#$A0
		BCS		loc_53FCB
		JMP		sub_53EC4
; ---------------------------------------------------------------------------
loc_53FCB:
		JMP		sub_8A04

; =============== S U B	R O U T	I N E =======================================
sub_53FCE:
		DEC		byte_5E0+$1E
		BNE		loc_53FD8
		LDA		#$00
		STA		byte_5E0
loc_53FD8:
		DEC		byte_55E,X
		BNE		loc_53FB9
		LDA		#$20
		STA		byte_541,X
		JSR		sub_89FB
		LDA		#$18
		STA		byte_55E,X
		LDA		#$03
loc_53FEC:
		STA		byte_55F,X
		JMP		loc_53FB9

; =============== S U B	R O U T	I N E =======================================
sub_53FF2:
		LDY		#$01
		LDA		byte_54F,X
		CMP		#$94
		BEQ		loc_53FFD
		LDY		#$00
loc_53FFD:
		STY		byte_600
		LDA		byte_543,X
		SEC
		SBC		#$10
		STA		byte_600+3
		LDA		_frames_counter
		AND		#$01
		BEQ		loc_54012
		INC		byte_543,X
loc_54012:
		DEC		byte_55E,X
		BNE		loc_53FB9
		LDA		#$00
		STA		byte_600
		LDA		#$1D
		STA		byte_541,X
		LDA		byte_55D
		STA		byte_55D,X
		JSR		sub_89FB
		LDA		#$00
		BEQ		loc_53FEC

; =============== S U B	R O U T	I N E =======================================
sub_5402E:
		DEC		byte_55E,X
		BNE		loc_53FB9
		LDA		#$1D
		STA		byte_541,X
		JSR		sub_89FB
		LDA		#$00
		STA		byte_55F,X
		LDA		byte_55D
		STA		byte_55D,X
		JMP		loc_53FB9

; =============== S U B	R O U T	I N E =======================================
sub_54049:
		LDA		_frames_counter
		AND		#$01
		TAY
		TXA
		CPY		#$01
		BNE		loc_5406D
		DEC		byte_55E,X
		BNE		loc_5406D
		LDA		#$05
		STA		byte_55F,X
		LDA		#$9A
		CPX		#$60
		BCS		loc_54070
		CPX		#$00
		BEQ		loc_54069
		LDA		#$9C
loc_54069:
		STA		byte_54F,X
		TXA
loc_5406D:
		JMP		loc_53FC0
; ---------------------------------------------------------------------------
loc_54070:
		LDA		#$9E
		BNE		loc_54069

; =============== S U B	R O U T	I N E =======================================
sub_54074:
		TXA
		JMP		loc_53FC0

; =============== S U B	R O U T	I N E =======================================
sub_54078:
		INC		byte_543,X
		CPX		#$60
		BEQ		loc_5408F
		DEC		byte_543,X
		DEC		byte_543,X
		LDA		byte_543,X
		CMP		#$98
		BCC		loc_54096
loc_5408C:
		JMP		loc_53FB9
; ---------------------------------------------------------------------------
loc_5408F:
		LDA		byte_543,X
		CMP		#$50
		BCC		loc_5408C
loc_54096:
		LDA		#$50
		STA		byte_5A0+3
		LDA		#$98
		STA		byte_5C0+3
		LDA		#$04
		STA		byte_55F,X
		LDA		#$D8
		STA		byte_55E,X
		LDA		#$00
		STA		byte_54B,X
		LDA		#$9D
		STA		byte_54F,X
		JMP		loc_5408C
; ---------------------------------------------------------------------------
_type_msg0C_ending:
		.WORD $8420
		.BYTE $23,$19,$1F,$27,$12,$0B,$20,$0F,$27,$1D,$0B,$20,$0F,$0E,$27,$1E
		.BYTE $12,$0F,$27,$21,$19,$1C,$16,$0E
		.BYTE $41
		.WORD $C820
		.BYTE $0D,$19,$18,$11,$1C,$0B,$1E,$1F,$16,$0B,$1E,$13,$19,$18,$1D
		.BYTE $41
		.WORD $0421
		.BYTE $1A,$0F,$0B,$0D,$0F,$27,$12,$0B,$1D,$27,$0B,$1C,$1C,$13,$20,$0F
		.BYTE $0E,$27,$0B,$1E,$27,$16,$0B,$1D,$1E
		.BYTE $40
_type_msg0E:
		.WORD $6421
		.BYTE $1A,$1C,$19,$11,$1C,$0B,$17,$17,$0F,$0E,$00,$0C,$23
		.BYTE $41
		.WORD $A921
		.BYTE $18,$0B,$18,$13,$21,$0B,$00,$18,$19,$00,$12,$13,$0E,$0F,$19
		.BYTE $40
_type_msg10:
		.WORD $6421
		.BYTE $0D,$12,$0B,$1C,$0B,$0D,$1E,$0F,$1C,$00,$0E,$0F,$1D,$13,$11,$18
		.BYTE $41
		.WORD $A921
		.BYTE $15,$0F,$13,$15,$19,$00,$0B,$18,$0E,$00,$12,$0B,$1C,$0B,$0D,$12
		.BYTE $0B,$18
		.BYTE $40
_type_msg12:
		.WORD $6421
		.BYTE $0D,$12,$0B,$1C,$0B,$0D,$1E,$0F,$1C,$00,$0E,$0F,$1D,$13,$11,$18
		.BYTE $41
		.WORD $A821
		.BYTE $11,$19,$15,$13,$11,$0F,$18,$00,$23,$19,$1D,$12,$13,$17,$19,$1E
		.BYTE $19
		.BYTE $40
_type_msg14:
		.WORD $6421
		.BYTE $1D,$19,$1F,$18,$0E,$00,$0E,$0F,$1D,$13,$11,$18
		.BYTE $41
		.WORD $A821
		.BYTE $0D,$12,$0B,$1C,$23,$00,$1D,$0B,$0E,$0B,$15,$13,$0D,$12,$13
		.BYTE $40
_type_msg16:
		.WORD $6421
		.BYTE $0E,$13,$1C,$0F,$0D,$1E,$0F,$0E,$00,$0C,$23
		.BYTE $41
		.WORD $AA21
		.BYTE $1A,$12,$0B,$24,$0F,$1C,$00,$0B,$1E,$1D,$1F,$15,$19
		.BYTE $40
_type_msg18:
		.WORD $6421
		.BYTE $20,$13,$1D,$1F,$0B,$16,$00,$0E,$0F,$1D,$13,$11,$18
		.BYTE $41
		.WORD $A821
		.BYTE $1D,$12,$13,$17,$19,$18,$0F,$1E,$0B,$00,$15,$0F,$18,$0D,$12,$0B
		.BYTE $18
		.BYTE $40
_type_msg1A:
		.WORD $6421
		.BYTE $20,$13,$1D,$1F,$0B,$16,$00,$0E,$0F,$1D,$13,$11,$18
		.BYTE $41
		.WORD $AA21
		.BYTE $0E,$0B,$13,$0C,$1F,$1E,$1D,$1F,$00,$17,$0B,$1C,$13
		.BYTE $40
_type_msg1C:
		.WORD $6421
		.BYTE $17,$1F,$1D,$13,$0D,$00,$0C,$23
		.BYTE $41
		.WORD $A721
		.BYTE $1C,$1F,$1D,$12,$0F,$1C,$00,$1D,$0B,$15,$0B,$17,$19,$1E,$19
		.BYTE $40
_type_msg1E:
		.WORD $6421
		.BYTE $17,$1F,$1D,$13,$0D,$00,$0C,$23
		.BYTE $41
		.WORD $A721
		.BYTE $13,$15,$1F,$00,$13,$15,$1F,$00,$17,$13,$24,$1F,$1E,$0B,$18,$13
		.BYTE $40
_type_msg20:
		.WORD $6421
		.BYTE $17,$1F,$1D,$13,$0D,$00,$0C,$23
		.BYTE $41
		.WORD $A921
		.BYTE $12,$0F,$20,$13,$17,$0F,$1E,$0B,$00,$1D,$0B,$1E,$19,$0F
		.BYTE $40
_type_msg22:
		.WORD $6421
		.BYTE $17,$1F,$1D,$13,$0D,$00,$0C,$23
		.BYTE $41
		.WORD $A921
		.BYTE $18,$0B,$18,$0E,$0B,$00,$0B,$0E,$0B,$0D,$12,$13
		.BYTE $40
_type_msg24:
		.WORD $6421
		.BYTE $1D,$1A,$0F,$0D,$13,$0B,$16,$00,$1E,$12,$0B,$18,$15,$1D
		.BYTE $41
		.WORD $A721
		.BYTE $12,$0B,$1D,$12,$13,$0C,$19,$1F,$00,$0B,$18,$0E,$00,$1D,$12,$13
		.BYTE $18,$19,$0C,$1F
		.BYTE $40
_tlm26_ending:
		.BYTE $21,$0C,$2F,$28,$28,$28,$28,$28,$28,$3F,$FE
_tlm27_ending:
		.BYTE $21,$2C,$3D,$28,$28,$9C,$9D,$00,$9E,$28,$FE
_tlm28_ending:
		.BYTE $21,$4C,$28,$28,$64,$5F,$8B,$8B,$56,$28,$FE
_tlm29_ending:
		.BYTE $21,$6C,$28,$28,$62,$7F,$8A,$8A,$63,$28,$FE
_tlm2A_ending:
		.BYTE $21,$8C,$48,$66,$4A,$4B,$00,$8B,$00,$BC,$FE
_tlm2B_ending:
		.BYTE $21,$AC,$27,$89,$5A,$5B,$00,$8A,$8A,$BB,$FE
_tlm2C_ending:
		.BYTE $21,$CC,$68,$69,$6A,$6B,$AA,$8B,$AA,$BA,$FE
_tlm2D_ending:
		.BYTE $21,$EC,$78,$79,$7A,$6B,$00,$8A,$8A,$B9,$FE
_tlm2E_ending:
		.BYTE $21,$0C,$2F,$28,$28,$28,$28,$28,$28,$3F,$FE
_tlm2F_ending:
		.BYTE $21,$2C,$3D,$28,$28,$28,$28,$28,$28,$28,$FE
_tlm30_ending:
		.BYTE $21,$4C,$28,$28,$28,$9C,$9D,$00,$8F,$28,$FE
_tlm31_ending:
		.BYTE $21,$6C,$28,$28,$64,$5F,$8B,$8B,$56,$28,$FE
_tlm32_ending:
		.BYTE $21,$8C,$48,$96,$65,$4B,$00,$8B,$9B,$7B,$FE
_tlm33_ending:
		.BYTE $21,$AC,$27,$89,$5A,$5B,$00,$8A,$8A,$BB,$FE
_tlm34_ending:
		.BYTE $21,$CC,$68,$69,$6A,$6B,$AA,$8B,$AA,$BA,$FE
_tlm35_ending:
		.BYTE $21,$EC,$78,$79,$7A,$6B,$00,$8A,$8A,$B9,$FE
_tlm36_ending:
		.BYTE $21,$0C,$2F,$28,$28,$28,$28,$28,$28,$3F,$FE
_tlm37_ending:
		.BYTE $21,$2C,$3D,$28,$28,$28,$28,$28,$28,$28,$FE
_tlm38_ending:
		.BYTE $21,$4C,$28,$28,$28,$28,$AD,$28,$28,$28,$FE
_tlm39_ending:
		.BYTE $21,$6C,$28,$28,$28,$AC,$AE,$AF,$9F,$28,$FE
_tlm3A_ending:
		.BYTE $21,$8C,$48,$8D,$7C,$A3,$00,$8B,$9B,$7B,$FE
_tlm3B_ending:
		.BYTE $21,$AC,$27,$97,$7D,$5B,$00,$8A,$8A,$BB,$FE
_tlm3C_ending:
		.BYTE $21,$CC,$68,$69,$6A,$6B,$AA,$8B,$AA,$BA,$FE
_tlm3D_ending:
		.BYTE $21,$EC,$78,$79,$7A,$6B,$00,$8A,$8A,$B9,$FE
_tlm3E_ending:
		.BYTE $21,$0C,$2F,$28,$28,$28,$28,$28,$28,$3F,$FE
_tlm3F_ending:
		.BYTE $21,$2C,$3D,$28,$28,$28,$28,$28,$28,$28,$FE
_tlm40_ending:
		.BYTE $21,$4C,$28,$28,$28,$28,$28,$28,$28,$28,$FE
_tlm41_ending:
		.BYTE $21,$6C,$28,$28,$28,$28,$28,$28,$28,$28,$FE
_tlm42_ending:
		.BYTE $21,$84,$3E,$3B,$3E,$3A,$3E,$3B,$3A,$3E,$48,$3A,$3E,$35,$3B,$3A
		.BYTE $48,$3A,$3B,$27,$3E,$35,$FE
_tlm43_ending:
		.BYTE $21,$A4,$27,$27,$4C,$4D,$27,$27,$27,$27,$27,$27,$27,$27,$37,$27
		.BYTE $27,$27,$2B,$2B,$2C,$27,$FE
_tlm44_ending:
		.BYTE $21,$C4,$27,$27,$5C,$5D,$27,$27,$27,$27,$27,$27,$27,$27,$27,$27
		.BYTE $27,$27,$27,$3A,$27,$27,$FE
_tlm45_ending:
		.BYTE $21,$E4,$27,$27,$50,$27,$27,$27,$27,$27,$27,$27,$27,$27,$55,$6C
		.BYTE $6D,$4E,$27,$27,$27,$27,$FE
_tlm46_ending:
		.BYTE $22,$04,$27,$27,$76,$27,$27,$27,$27,$27,$27,$27,$54,$51,$8A,$00
		.BYTE $00,$47,$55,$58,$52,$4E,$27,$27,$27,$53,$A8,$27,$27,$27,$FE
_tlm47_ending:
		.BYTE $22,$24,$33,$75,$76,$44,$51,$52,$53,$54,$52,$51,$00,$00,$00,$00
		.BYTE $00,$00,$00,$00,$00,$47,$58,$52,$4E,$57,$B8,$44,$33,$75,$FE
_tlm48_ending:
		.BYTE $22,$44,$84,$85,$95,$95,$86,$94,$86,$86,$00,$95,$86,$00,$00,$00
		.BYTE $95,$94,$95,$95,$00,$00,$95,$95,$86,$86,$86,$94,$84,$85,$FE
_tlm49_ending:
		.BYTE $22,$64,$94,$94,$95,$94,$95,$94,$27,$94,$95,$94,$95,$94,$95,$94
		.BYTE $94,$95,$94,$94,$95,$94,$94,$27,$94,$95,$95,$A4,$B6,$A4,$FE
